### ISSUE TITLE
test files in sub directory does not seem to be loaded in Rails 5.2 environment

### ISSUE THREAD

**Issue by bsdmad** [test-unit/test-unit-rails#22]
Hello,

With test-unit-rails 5.2.2 and Rails 5.2.x, test files in sub directory doesn't seem to be loaded.
For test/controllers/api/v1/foo_controller_test.rb, I have confirmed follwings with same settings: 

1. test-unit-rails 5.2.2 and Rails 5.1.6 - OK
1. test-unit-rails 5.2.2 and Rails 5.2.0/5.2.1 - NG

Note: with minitest, the problem doesn't occur.

Does test-unit-rails 5.2.2 already support Rails 5.2?

**Comment by bsdmad** [comment]
Both ```bin/rake test``` and ```bin/rails test``` make same result.

**Comment by kou** [comment]
Can you provide a Rails application that reproduces this case?

**Comment by bsdmad** [comment]
Mm, it's not so easy...

**Comment by bsdmad** [comment]
Sorry but I could not work for this issue.
